# Generated by Django 4.2.8 on 2025-12-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("gold", models.FloatField(default=100.0)),
                ("reputation", models.FloatField(default=0.0)),
                ("max_guests", models.IntegerField(default=5)),
                ("total_income_multiplier", models.FloatField(default=1.0)),
                ("auto_clean_enabled", models.BooleanField(default=False)),
                ("game_speed", models.FloatField(default=1.0)),
                ("tavern_unlocked", models.BooleanField(default=False)),
                ("item_inventory", models.JSONField(default=dict)),
                ("ingredient_inventory", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Game State",
                "verbose_name_plural": "Game States",
                "ordering": ["-last_update"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_drop_chance", models.FloatField(default=0.1)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "ordering": ["rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="TavernItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("food", "Food"), ("beverage", "Beverage")],
                        max_length=20,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("good", "Good"),
                            ("fine", "Fine"),
                            ("exquisite", "Exquisite"),
                            ("legendary", "Legendary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cost", models.FloatField(default=0.0)),
                ("gold_bonus", models.FloatField(default=0.0)),
                ("patience_bonus", models.FloatField(default=0.0)),
                ("reputation_bonus", models.FloatField(default=0.0)),
                ("satisfaction_bonus", models.FloatField(default=0.0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tavern Item",
                "verbose_name_plural": "Tavern Items",
                "ordering": ["item_type", "quality"],
            },
        ),
        migrations.CreateModel(
            name="UpgradeTemplate",
            fields=[
                (
                    "upgrade_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("cost", models.FloatField(default=0.0)),
                ("effect_type", models.CharField(max_length=50)),
                ("effect_value", models.FloatField(default=0.0)),
                (
                    "required_upgrade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocks",
                        to="game_api.upgradetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upgrade Template",
                "verbose_name_plural": "Upgrade Templates",
                "ordering": ["cost"],
            },
        ),
        migrations.CreateModel(
            name="RoomTypeTemplate",
            fields=[
                (
                    "room_type_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("base_cost", models.FloatField(default=50.0)),
                ("income_multiplier", models.FloatField(default=1.0)),
                ("emoji", models.CharField(default="🏠", max_length=10)),
                (
                    "required_upgrade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocks_room_types",
                        to="game_api.upgradetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Type Template",
                "verbose_name_plural": "Room Type Templates",
                "ordering": ["base_cost"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("occupied", models.BooleanField(default=False)),
                ("cleanliness", models.FloatField(default=100.0)),
                (
                    "game_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="game_api.gamestate",
                    ),
                ),
                (
                    "room_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="game_api.roomtypetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.CreateModel(
            name="RecipeTemplate",
            fields=[
                (
                    "recipe_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("required_ingredients", models.JSONField(default=list)),
                ("cost_to_unlock", models.FloatField(default=0.0)),
                ("ingredients_cost", models.FloatField(default=0.0)),
                ("discoverable", models.BooleanField(default=True)),
                ("auto_unlocked", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_templates",
                        to="game_api.tavernitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Template",
                "verbose_name_plural": "Recipe Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "guest_type",
                    models.CharField(
                        choices=[
                            ("peasant", "Peasant"),
                            ("merchant", "Merchant"),
                            ("noble", "Noble"),
                            ("adventurer", "Adventurer"),
                            ("wizard", "Wizard"),
                            ("bandit", "Bandit"),
                            ("monk", "Monk"),
                            ("bard", "Bard"),
                            ("dragon_disguised", "Dragon (Disguised)"),
                            ("beggar", "Beggar"),
                            ("prince", "Prince"),
                            ("thief", "Thief"),
                            ("scholar", "Scholar"),
                            ("drunk", "Drunk"),
                            ("ghost", "Ghost"),
                        ],
                        max_length=20,
                    ),
                ),
                ("patience", models.FloatField(default=100.0)),
                ("satisfaction", models.FloatField(default=50.0)),
                ("gold_per_tick", models.FloatField(default=1.0)),
                ("reputation_bonus", models.FloatField(default=0.1)),
                ("stay_duration", models.IntegerField(default=10)),
                ("fed", models.BooleanField(default=False)),
                ("served_drink", models.BooleanField(default=False)),
                (
                    "food_served",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "beverage_served",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="game_api.gamestate",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_guest",
                        to="game_api.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest",
                "verbose_name_plural": "Guests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Upgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased", models.BooleanField(default=False)),
                (
                    "game_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="game_api.gamestate",
                    ),
                ),
                (
                    "upgrade_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="game_api.upgradetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upgrade",
                "verbose_name_plural": "Upgrades",
                "unique_together": {("game_state", "upgrade_template")},
            },
        ),
        migrations.CreateModel(
            name="PlayerRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovered", models.BooleanField(default=False)),
                ("discovered_at", models.DateTimeField(blank=True, null=True)),
                ("unlocked", models.BooleanField(default=False)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("times_crafted", models.IntegerField(default=0)),
                (
                    "game_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_recipes",
                        to="game_api.gamestate",
                    ),
                ),
                (
                    "recipe_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_instances",
                        to="game_api.recipetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Recipe",
                "verbose_name_plural": "Player Recipes",
                "ordering": ["-discovered_at"],
                "unique_together": {("game_state", "recipe_template")},
            },
        ),
    ]
