# Generated by Django 4.2.8 on 2025-12-12 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="upgrade",
            options={
                "verbose_name": "Purchased Upgrade",
                "verbose_name_plural": "Purchased Upgrades",
            },
        ),
        migrations.RemoveField(
            model_name="upgrade",
            name="purchased",
        ),
        migrations.AddField(
            model_name="upgrade",
            name="purchased_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="upgrade",
            name="game_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_upgrades",
                to="game_api.gamestate",
            ),
        ),
        migrations.AlterField(
            model_name="upgrade",
            name="upgrade_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="player_purchases",
                to="game_api.upgradetemplate",
            ),
        ),
    ]
