# Generated by Django 4.2.8 on 2025-12-12 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game_api", "0002_alter_upgrade_options_remove_upgrade_purchased_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="last_offline_earnings",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="last_offline_hours",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="last_online",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="map_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="map_y",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="max_offline_hours",
            field=models.FloatField(default=12.0),
        ),
        migrations.AlterField(
            model_name="guest",
            name="guest_type",
            field=models.CharField(
                choices=[
                    ("peasant", "Peasant"),
                    ("merchant", "Merchant"),
                    ("noble", "Noble"),
                    ("adventurer", "Adventurer"),
                    ("wizard", "Wizard"),
                    ("sorcerer", "Sorcerer"),
                    ("witch", "Witch"),
                    ("alchemist", "Alchemist"),
                    ("necromancer", "Necromancer"),
                    ("knight", "Knight"),
                    ("paladin", "Paladin"),
                    ("ranger", "Ranger"),
                    ("barbarian", "Barbarian"),
                    ("samurai", "Samurai"),
                    ("bandit", "Bandit"),
                    ("thief", "Thief"),
                    ("assassin", "Assassin"),
                    ("smuggler", "Smuggler"),
                    ("monk", "Monk"),
                    ("priest", "Priest"),
                    ("cleric", "Cleric"),
                    ("druid", "Druid"),
                    ("bard", "Bard"),
                    ("jester", "Jester"),
                    ("minstrel", "Minstrel"),
                    ("actor", "Actor"),
                    ("blacksmith", "Blacksmith"),
                    ("carpenter", "Carpenter"),
                    ("jeweler", "Jeweler"),
                    ("tailor", "Tailor"),
                    ("scholar", "Scholar"),
                    ("scribe", "Scribe"),
                    ("librarian", "Librarian"),
                    ("historian", "Historian"),
                    ("dragon_disguised", "Dragon (Disguised)"),
                    ("vampire", "Vampire"),
                    ("werewolf", "Werewolf"),
                    ("elf", "Elf"),
                    ("dwarf", "Dwarf"),
                    ("halfling", "Halfling"),
                    ("orc", "Orc"),
                    ("beggar", "Beggar"),
                    ("prince", "Prince"),
                    ("pirate", "Pirate"),
                    ("spy", "Spy"),
                    ("drunk", "Drunk"),
                    ("ghost", "Ghost"),
                ],
                max_length=20,
            ),
        ),
    ]
