# Generated by Django 4.2.8 on 2025-12-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_api", "0003_gamestate_last_offline_earnings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="customers_served",
            field=models.IntegerField(default=0),
        ),
    ]
