# Generated by Django 4.2.8 on 2025-12-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_api", "0004_room_customers_served"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="is_purchasable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="market_price",
            field=models.FloatField(default=0.0),
        ),
    ]
