# Generated by Django 4.2.8 on 2025-12-13 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game_api", "0005_ingredient_is_purchasable_ingredient_market_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgradetemplate",
            name="duration_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="upgradetemplate",
            name="is_consumable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="upgradetemplate",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="upgradetemplate",
            name="premium_price_cents",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PremiumPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("amount_cents", models.IntegerField()),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "game_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_purchases",
                        to="game_api.gamestate",
                    ),
                ),
                (
                    "upgrade_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="game_api.upgradetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Premium Purchase",
                "verbose_name_plural": "Premium Purchases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="game_api_pr_stripe__c2d1fb_idx",
                    ),
                    models.Index(
                        fields=["game_state", "status"],
                        name="game_api_pr_game_st_87f6f9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiveBuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "game_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_buffs",
                        to="game_api.gamestate",
                    ),
                ),
                (
                    "upgrade_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_instances",
                        to="game_api.upgradetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Buff",
                "verbose_name_plural": "Active Buffs",
                "ordering": ["-activated_at"],
                "indexes": [
                    models.Index(
                        fields=["game_state", "active", "expires_at"],
                        name="game_api_ac_game_st_77d70e_idx",
                    )
                ],
            },
        ),
    ]
