# Generated by Django 5.2.9 on 2025-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0007_guest_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='inn_name',
            field=models.CharField(default='Inn', max_length=1000),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='map_world',
            field=models.CharField(default='toril', max_length=1000),
        ),
    ]
