# Generated by Django 4.2.8 on 2025-12-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_api", "0008_gamestate_inn_name_gamestate_map_world"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgradetemplate",
            name="operational_cost_per_tick",
            field=models.FloatField(default=0.0),
        ),
    ]
