# Generated by Django 4.2.8 on 2025-12-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game_api", "0010_add_achievements"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtypetemplate",
            name="species_bonuses",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="roomtypetemplate",
            name="type_bonuses",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="playerachievement",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_achievements",
                to="game_api.achievement",
            ),
        ),
    ]
